/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.patient_management;

import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Tharindu Kumesh
 */
public class InsertPatient extends javax.swing.JFrame {
    File file;
    /**
     * Creates new form InsertPatient
     */
    
    
    DBConnection db=new DBConnection();
    ArrayList<String> list=new ArrayList<>();
    
    ArrayList<String> hos_idlist=new ArrayList<>();
    
     ArrayList<String> doc_idlist=new ArrayList<>();
     
     ArrayList<String> drug_code=new ArrayList<>();
      
         String s="";
         
        
       // String[] drug={"Drug1","Drug2","Drug3","Drug4", "Drug5"};
    
    public InsertPatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        labelInsert = new javax.swing.JLabel();
        labellastname = new javax.swing.JLabel();
        buttnOK = new javax.swing.JButton();
        buttnOK1 = new javax.swing.JButton();
        lname = new javax.swing.JTextField();
        labelP_ID = new javax.swing.JLabel();
        labelDOB = new javax.swing.JLabel();
        patientIdText = new javax.swing.JTextField();
        labelfirstname = new javax.swing.JLabel();
        labelAddress1 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        midname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        issuedDate = new com.toedter.calendar.JDateChooser();
        labelAddress2 = new javax.swing.JLabel();
        allergies = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        disease = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        hospitalId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        drugCodeCombo = new javax.swing.JComboBox<>();
        dosageCombo = new javax.swing.JComboBox<>();
        frequantCombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        doctorId = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        imageLbl = new javax.swing.JLabel();
        hosIdCombo = new javax.swing.JComboBox<>();
        docIdCombo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();

        jLabel6.setText("jLabel6");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelInsert.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelInsert.setText("PATIENT DETAILS");
        getContentPane().add(labelInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 24, 242, -1));

        labellastname.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        labellastname.setText("Last Name");
        getContentPane().add(labellastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 215, 92, -1));

        buttnOK.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttnOK.setText("Back");
        buttnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttnOKActionPerformed(evt);
            }
        });
        getContentPane().add(buttnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 725, 83, 37));

        buttnOK1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttnOK1.setText("ADD");
        buttnOK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttnOK1ActionPerformed(evt);
            }
        });
        getContentPane().add(buttnOK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1063, 726, 83, 37));
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 212, 257, -1));

        labelP_ID.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        labelP_ID.setText("Patient ID");
        getContentPane().add(labelP_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 104, -1, -1));

        labelDOB.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        labelDOB.setText("Date of Birth");
        getContentPane().add(labelDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 252, 92, -1));

        patientIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIdTextActionPerformed(evt);
            }
        });
        getContentPane().add(patientIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 101, 257, -1));

        labelfirstname.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        labelfirstname.setText("First Name");
        getContentPane().add(labelfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 153, 92, -1));

        labelAddress1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        labelAddress1.setText("Issued Date");
        getContentPane().add(labelAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 438, 69, -1));

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 150, 257, -1));

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 296, 257, -1));
        getContentPane().add(midname, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 178, 257, -1));

        jLabel1.setText("Mid Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 181, -1, -1));

        dob.setToolTipText("");
        dob.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 252, 257, -1));

        issuedDate.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(issuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 438, 257, -1));

        labelAddress2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        labelAddress2.setText("Address");
        getContentPane().add(labelAddress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 306, 69, -1));
        getContentPane().add(allergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 507, 257, -1));

        jLabel2.setText("Allergies");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 510, -1, -1));
        getContentPane().add(disease, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 469, 257, -1));

        jLabel3.setText("Disease");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 472, -1, -1));
        getContentPane().add(hospitalId, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 571, 257, -1));

        jLabel4.setText("Hospital ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 574, -1, -1));

        jLabel5.setText("Contact");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 33, -1, -1));
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 30, 502, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Drug Details");

        drugCodeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Drug Code" }));
        drugCodeCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drugCodeComboMouseClicked(evt);
            }
        });

        dosageCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dosage", "1/2", "1", "1 and 1/2", "2", "2 and 1/2", "3", "3 and 1/2" }));

        frequantCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frequent", "2 times per day", "3 times per day", "6 hours", "8 hours", "10 hours" }));

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane2.setViewportView(textArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(drugCodeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(dosageCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(frequantCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drugCodeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dosageCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frequantCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 70, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(969, 725, 84, 38));

        jLabel8.setText("Doctor ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 711, -1, -1));
        getContentPane().add(doctorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 708, 257, -1));

        jButton3.setText("Browse");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1071, 526, -1, 58));
        getContentPane().add(imageLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 469, 465, 233));

        hosIdCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hospital ID" }));
        hosIdCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hosIdComboMouseClicked(evt);
            }
        });
        getContentPane().add(hosIdCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 616, 257, -1));

        docIdCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor ID" }));
        docIdCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docIdComboMouseClicked(evt);
            }
        });
        getContentPane().add(docIdCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 741, 257, -1));

        jPanel2.setBackground(new java.awt.Color(152, 215, 215));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1160, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttnOKActionPerformed
       
         this.setVisible(false);
        new InsertMain().setVisible(true);
        

    }//GEN-LAST:event_buttnOKActionPerformed

    private void buttnOK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttnOK1ActionPerformed
      
        
        String num=contact.getText();
        
        if(num.charAt(0)=='0' && num.length()==10 && num.matches("[0-9]+")){
        
        try{
           
        db.insertPatient(patientIdText.getText(),fname.getText(),midname.getText(),lname.getText(),((JTextField)dob.getDateEditor().getUiComponent()).getText(),disease.getText(),address.getText(),((JTextField)issuedDate.getDateEditor().getUiComponent()).getText(),allergies.getText(),String.valueOf(hosIdCombo.getSelectedItem()),num,s,String.valueOf(docIdCombo.getSelectedItem()));
         FileInputStream fin = new FileInputStream(file);
            int len = (int)file.length();
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/patient_management","root","");
            //PreparedStatement ps = con.prepareStatement("insert into patient(photo) values (?) where id = 001;");
            PreparedStatement ps = con.prepareStatement("update patient set photo=(?) where id = '"+patientIdText+"';");
            ps.setBinaryStream(1, fin,len);
            int status = ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Succusfully Inserted Patient !!! ");
        
        }catch(Exception e){
        
            e.printStackTrace();
        }
        
        }else{
        
        JOptionPane.showMessageDialog(this, "Invalid Contact Number !! ");
        
        }
        
    }//GEN-LAST:event_buttnOK1ActionPerformed

    private void patientIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIdTextActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        textArea.setText("");
        
       // int x=drugCodeCombo.getSelectedIndex();
        
        
        
       list.add(drugCodeCombo.getSelectedItem()+"    "/*+drug[x-1]+"   "*/+dosageCombo.getSelectedItem()+"     "+frequantCombo.getSelectedItem());
       
      if(list.size() == 0){
           
           s=list.get(list.size()-1);
           
           
       
       }else{
       s=s+"\n"+list.get(list.size()-1);
          System.out.println("");
       }
       
        for(int i=0; i<list.size(); i++){
        
           
           textArea.setText(s);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        patientIdText.setText("");
        fname.setText("");
        midname.setText("");
        lname.setText("");
        dob.cleanup();
        address.setText("");
        issuedDate.cleanup();
        disease.setText("");
        allergies.setText("");
        hospitalId.setText("");
        contact.setText("");
        textArea.setText("");
             
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
        filechooser.showOpenDialog(this);
        file = filechooser.getSelectedFile();
        String path = file.getAbsolutePath();
        ImageIcon icon = new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(imageLbl.getWidth(),imageLbl.getHeight(),Imageview.NORMAL));
       
        imageLbl.setIcon(icon);
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void hosIdComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hosIdComboMouseClicked
       try{
       
           hos_idlist=db.getHospitalid();
           
           for(int x=0; x<hos_idlist.size(); x++){
           
           hosIdCombo.addItem(hos_idlist.get(x));
               
               
           }
           
           
           
          // hospitalId.setText(String.valueOf(hosIdCombo.getSelectedItem()));
           
       
       }catch(Exception e){
       
           System.out.println("Exception in Get Hospital ID");
       
       }
    }//GEN-LAST:event_hosIdComboMouseClicked

    private void docIdComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docIdComboMouseClicked
       
         try{
       
           doc_idlist=db.getDoctorid();
           
           for(int x=0; x<doc_idlist.size(); x++){
           
           docIdCombo.addItem(doc_idlist.get(x));
               
               
           }
           
           
            //doctorId.setText(String.valueOf(docIdCombo.getSelectedItem()));
           
       
       }catch(Exception e){
       
           System.out.println("Exception in Get Doctor ID");
       
       }
        
    }//GEN-LAST:event_docIdComboMouseClicked

    private void drugCodeComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drugCodeComboMouseClicked
       
        
        
        try{
        
           drug_code=db.getDrugCode();
           
           for(int x=0; x<drug_code.size(); x++){
           
           drugCodeCombo.addItem(drug_code.get(x));
           
           }
            
        }catch(Exception e){
        
        
        }
        
        
    }//GEN-LAST:event_drugCodeComboMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JTextField allergies;
    private javax.swing.JButton buttnOK;
    private javax.swing.JButton buttnOK1;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField disease;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JComboBox<String> docIdCombo;
    private javax.swing.JTextField doctorId;
    private javax.swing.JComboBox<String> dosageCombo;
    private javax.swing.JComboBox<String> drugCodeCombo;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> frequantCombo;
    private javax.swing.JComboBox<String> hosIdCombo;
    private javax.swing.JTextField hospitalId;
    private javax.swing.JLabel imageLbl;
    private com.toedter.calendar.JDateChooser issuedDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelAddress1;
    private javax.swing.JLabel labelAddress2;
    private javax.swing.JLabel labelDOB;
    private javax.swing.JLabel labelInsert;
    private javax.swing.JLabel labelP_ID;
    private javax.swing.JLabel labelfirstname;
    private javax.swing.JLabel labellastname;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField midname;
    private javax.swing.JTextField patientIdText;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
