/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.patient_management;

import static com.mycompany.patient_management.Imageview.jLabelimage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.Period;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Tharindu Kumesh
 */
public class SearchPatient extends javax.swing.JFrame {

    /**
     * Creates new form SearchPatient
     */
    
    
    DBConnection db= new DBConnection();
    java.awt.Image im;
    
    ArrayList<String> list=new ArrayList<>();
    
    
    
    public SearchPatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        yearText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        issuedDateText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        diseaseText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        allergiesText = new javax.swing.JTextField();
        hospitalText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        contactText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaText = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        idText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        doctorText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Patient Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 11, -1, 34));
        getContentPane().add(addressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 167, 260, 91));

        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 104, -1, -1));

        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 204, -1, -1));

        jLabel5.setText("Age");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 343, -1, -1));
        getContentPane().add(yearText, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 333, 260, 37));

        jLabel6.setText("Disease");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 449, -1, -1));
        getContentPane().add(issuedDateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 673, 246, 38));

        jLabel7.setText("Allergies");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 534, -1, -1));
        getContentPane().add(diseaseText, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 438, 246, 38));

        jLabel8.setText("Issued Date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 684, -1, -1));
        getContentPane().add(allergiesText, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 523, 246, 38));
        getContentPane().add(hospitalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 72, 215, 33));

        jLabel9.setText("Hospital");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 80, -1, -1));

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(878, 733, -1, -1));
        getContentPane().add(contactText, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 168, 215, 36));

        jLabel10.setText("Contact");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 178, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Drugs");

        areaText.setColumns(20);
        areaText.setRows(5);
        jScrollPane1.setViewportView(areaText);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel11)
                .addContainerGap(218, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 361, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 13, -1, -1));
        getContentPane().add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 90, 260, 45));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 13, -1, 66));
        getContentPane().add(doctorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 118, 215, 32));

        jLabel12.setText("Doctor");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 129, -1, -1));

        jLabel13.setBackground(java.awt.Color.white);
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 222, 202, 133));

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(989, 733, -1, -1));

        jPanel3.setBackground(new java.awt.Color(152, 215, 215));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
       new MainWindow().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        try{
        
            
            if(db.checkPatientId(idText.getText())){
            
        
        try{
               list= db.searchPatient(idText.getText());
               nameText.setText(list.get(0)+" "+list.get(1)+" "+list.get(2));
               addressText.setText(list.get(5));
               //yearText.setText(list.get(3));
               
               // deriving the age of the patient
               
               String DOB[]=list.get(3).split("-");
               
               int year=Integer.valueOf(DOB[0]);
               int month=Integer.valueOf(DOB[1]);
               int day=Integer.valueOf(DOB[2]);
               
               LocalDate selectedDate=LocalDate.of(year, month, day);
               LocalDate currentDate=LocalDate.now();
               
               int resultYear=Period.between(selectedDate, currentDate).getYears();
                int resultMonth=Period.between(selectedDate, currentDate).getMonths();
                 int resultDay=Period.between(selectedDate, currentDate).getDays();
                 
                 
                 yearText.setText(resultYear+" years "+resultMonth+" month "+resultDay+" Days ");
               
               
               diseaseText.setText(list.get(4));
               allergiesText.setText(list.get(7));
               issuedDateText.setText(list.get(6));
               
               hospitalText.setText(db.getHospital(list.get(8)));
               contactText.setText(list.get(9));
               areaText.setText(list.get(10));
               doctorText.setText(db.getDoctor(list.get(11)));
               
               
               
               
               
        }catch(Exception e){
        
            System.out.println("Exception in get Patient Method");
        }
        
        try {
            
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/patient_management","root","");
            Statement s = (Statement) con.createStatement();
            ResultSet rs = s.executeQuery("select * from patient where id = '"+idText.getText()+"';");
            //ResultSet rs = s.executeQuery("select photo from patient where id = id;");
            if(rs.next()){
                byte[] img = rs.getBytes("photo");
                ImageIcon image = new ImageIcon(img);
                im = image.getImage();
                java.awt.Image myImg = im.getScaledInstance(jLabel13.getWidth(),jLabel13.getHeight(), Imageview.NORMAL);
                ImageIcon newImage = new ImageIcon(myImg);
                jLabel13.setIcon(newImage);
                
            
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Imageview.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            }else{
            
            JOptionPane.showMessageDialog(this,"Patient Id not Found !!! ");
            }
        
    }catch(Exception e){


            System.out.println("Exception in cheking the Patient ID ");
        
  }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        FullImage fi = new FullImage();
        fi.setVisible(true);
        java.awt.Image myImg = im.getScaledInstance(FullImage.fullimg.getWidth(),FullImage.fullimg.getHeight(), Imageview.NORMAL);
                ImageIcon newImage = new ImageIcon(myImg);
        FullImage.fullimg.setIcon(newImage);
        
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        addressText.setText("");
        allergiesText.setText("");
        areaText.setText("");        
        contactText.setText("");
        diseaseText.setText(""); 
        doctorText.setText(""); 
        hospitalText.setText("");
        idText.setText("");
        issuedDateText.setText("");
        nameText.setText("");
        yearText.setText(""); 
        jLabel3.setIcon(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField allergiesText;
    private javax.swing.JTextArea areaText;
    private javax.swing.JTextField contactText;
    private javax.swing.JTextField diseaseText;
    private javax.swing.JTextField doctorText;
    private javax.swing.JTextField hospitalText;
    private javax.swing.JTextField idText;
    private javax.swing.JTextField issuedDateText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField yearText;
    // End of variables declaration//GEN-END:variables
}
